site_name: birdhouse
site_description: "birdhouse: tools for OGC API processes"
site_author: the birdhouse community
copyright: "&copy; 2024 birdhouse development team"
site_url: https://bird-house.github.io/
repo_url: https://github.com/bird-house/bird-house.github.io
docs_dir: docs

nav:
    - Home: index.md
    - Community: community/index.md
    - Documentation: documentation.md
    - Demo: https://github.com/bird-house/nandu
    - Code: https://github.com/bird-house
    - Download: download.md
    - Development: development/index.md

use_directory_urls: true

theme:
    name: mkdocs

plugins:
    - search
